version: "3"
services:
    backend01:
        build:
            context: ./api
            dockerfile: Dockerfile
        environment:
            - APP_NAME=backend01
            - POST_LISTS=01,01,01
    backend02:
        build:
            context: ./api
            dockerfile: Dockerfile
        environment:
            - APP_NAME=backend02
            - POST_LISTS=02,02,02
    backend03:
        build:
            context: ./api
            dockerfile: Dockerfile
        environment:
            - APP_NAME=backend03
            - POST_LISTS=03,03,03
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        environment:
            - PUBLIC_API_HOST=<host for accessing the backend>
            - PUBLIC_API_PORT=<port for accessing the backend>
